const ACTIVITIES = [
  {
    id: "cardboard-town",
    title: "A tiny cardboard town",
    category: "Make & create",
    description: "Turn yesterday’s boxes into a whole new world.",
    age: [4, 12],
    time: 45,
    setting: "Indoors",
    mess: "Medium",
    color: "#eddfc9",
    art: "town",
    badge: "A little imagination",
    materials: [
      "Clean cardboard boxes",
      "Washable markers",
      "Paper tape",
      "Child-safe scissors",
    ],
    steps: [
      "Choose a few boxes and imagine the buildings your town needs.",
      "Ask a grown-up to cut doors and windows in the thicker cardboard.",
      "Draw rooftops, shop signs, and colorful details.",
      "Arrange your buildings and add paper roads. Make up a story about who lives there.",
    ],
    tip: "Keep building over several days. A cereal box makes a lovely library!",
  },
  {
    id: "nature-crowns",
    title: "Nature crowns",
    category: "Explore nature",
    description: "A little fresh air. A very royal afternoon.",
    age: [4, 12],
    time: 20,
    setting: "Outdoors",
    mess: "Low",
    color: "#e0e6d3",
    art: "crown",
    badge: "Fresh-air favorite",
    materials: [
      "A strip of recycled card",
      "Paper tape",
      "Fallen leaves and flowers",
      "Glue stick",
    ],
    steps: [
      "Take a walk and collect fallen leaves and flowers with a grown-up.",
      "Measure a strip of card around your head, leaving a little overlap.",
      "Lay the strip flat and glue your treasures along it.",
      "Let it dry, then tape the ends together and begin your royal parade.",
    ],
    tip: "Leave growing plants for wildlife and avoid unfamiliar plants. Wash hands after collecting.",
  },
  {
    id: "rainbow-prints",
    title: "Rainbow sponge prints",
    category: "Make & create",
    description: "Big colors and happy little masterpieces.",
    age: [2, 8],
    time: 20,
    setting: "Indoors",
    mess: "High",
    color: "#f0d9cf",
    art: "rainbow",
    badge: "Let’s get colorful",
    materials: [
      "Washable, age-appropriate paint",
      "A clean sponge",
      "Large paper",
      "A tray and table covering",
    ],
    steps: [
      "Cover your workspace and put a large sheet of paper on the table.",
      "A grown-up adds stripes of washable paint to a damp sponge.",
      "Press or sweep the sponge across the paper to make a rainbow.",
      "Try new shapes and let your masterpiece dry.",
    ],
    tip: "For toddlers, use a large sponge and supervise closely. Paint belongs on the paper, not in mouths.",
  },
  {
    id: "paper-rockets",
    title: "Ready, set, paper rockets!",
    category: "Little scientists",
    description: "Small rockets. Out-of-this-world discoveries.",
    age: [6, 12],
    time: 30,
    setting: "Indoors",
    mess: "Low",
    color: "#dce3ea",
    art: "rocket",
    badge: "Wonder in the making",
    materials: [
      "Paper",
      "Paper tape",
      "A drinking straw",
      "Child-safe scissors",
    ],
    steps: [
      "Wrap a small rectangle of paper loosely around the straw and tape the seam.",
      "Slide it off and fold and tape one end closed.",
      "Add paper fins, then slide the open end onto the straw.",
      "Point toward a clear space and blow through the straw. Compare different fin shapes.",
    ],
    tip: "Never aim at faces or animals. Give each child their own straw.",
  },
  {
    id: "living-room-trail",
    title: "The living room adventure",
    category: "Move & play",
    description: "An ordinary room becomes an epic expedition.",
    age: [2, 8],
    time: 15,
    setting: "Indoors",
    mess: "Low",
    color: "#e9ddca",
    art: "trail",
    badge: "Energy, well spent",
    materials: ["Floor cushions", "A blanket", "Paper stepping stones"],
    steps: [
      "Clear a safe space on the floor with a grown-up.",
      "Arrange flat cushions and paper stepping stones into a short trail.",
      "Imagine a river to step across and a blanket island to reach.",
      "Take turns choosing new ways to travel: slow steps, a gentle crawl, or a silly walk.",
    ],
    tip: "Keep everything at floor level and use non-slip surfaces. Avoid jumping from furniture.",
  },
  {
    id: "bug-hotel",
    title: "A little hotel for bugs",
    category: "Explore nature",
    description: "Make a cozy stop for your garden’s tiny guests.",
    age: [6, 12],
    time: 45,
    setting: "Outdoors",
    mess: "Medium",
    color: "#dbe2cf",
    art: "hotel",
    badge: "For curious minds",
    materials: [
      "A clean open wooden box",
      "Fallen twigs",
      "Pine cones",
      "Dry leaves",
    ],
    steps: [
      "Find a sheltered spot outdoors with a grown-up.",
      "Place your box on its side at ground level.",
      "Loosely layer twigs, dry leaves, and pine cones inside.",
      "Visit quietly over the next few days to look for guests without disturbing them.",
    ],
    tip: "Observe insects without handling them. Avoid sharp wood and wash hands when finished.",
  },
  {
    id: "shadow-stories",
    title: "Once upon a shadow",
    category: "Move & play",
    description: "Let little hands tell tall tales on the wall.",
    age: [4, 12],
    time: 15,
    setting: "Indoors",
    mess: "Low",
    color: "#e3dfee",
    art: "shadow",
    badge: "Just add a story",
    materials: ["A flashlight", "A blank wall", "Your hands"],
    steps: [
      "Dim the lights and ask a grown-up to hold a flashlight toward a clear wall.",
      "Put a hand between the light and the wall. What shape appears?",
      "Try a bird, a rabbit, or a creature nobody has seen before.",
      "Take turns adding a character to a story.",
    ],
    tip: "Never shine the light into anyone’s eyes. Leave enough room lighting to move safely.",
  },
  {
    id: "sink-float",
    title: "Will it sink or float?",
    category: "Little scientists",
    description: "Tiny experiments for very big questions.",
    age: [2, 8],
    time: 15,
    setting: "Outdoors",
    mess: "Medium",
    color: "#d5e6e4",
    art: "water",
    badge: "The 15-minute fix",
    materials: [
      "A shallow bowl of water",
      "A large leaf",
      "A wooden spoon",
      "A large smooth stone",
      "A towel",
    ],
    steps: [
      "Place a shallow bowl on a stable surface beside a grown-up.",
      "Choose large, safe household objects and predict what each one will do.",
      "Gently lower one object at a time into the water and observe.",
      "Sort the objects into sinkers and floaters, then empty the bowl together.",
    ],
    tip: "An adult must stay within arm’s reach around water. Use objects too large to swallow and empty water immediately afterward.",
  },
  {
    id: "leaf-rubbings",
    title: "Secret patterns of leaves",
    category: "Make & create",
    description: "Discover the beautiful details hiding in plain sight.",
    age: [4, 12],
    time: 15,
    setting: "Indoors",
    mess: "Low",
    color: "#ece5c9",
    art: "leaves",
    badge: "Simple little joys",
    materials: ["Fallen leaves", "Paper", "Large crayons"],
    steps: [
      "Choose a few fallen leaves with different shapes.",
      "Place one leaf vein-side up beneath a sheet of paper.",
      "Rub gently across the paper with the side of a crayon.",
      "Compare the patterns and combine them into a colorful leaf picture.",
    ],
    tip: "Use familiar, non-irritating leaves and wash your hands afterward.",
  },
];
if (typeof module !== "undefined") module.exports = ACTIVITIES;
